Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Aluno   : Nicolas Garcia de Souza Santos
// Descrição   : Descreve se um número é impar ou par
// Data atual  : 26/07/2022

Var

numero: inteiro

Inicio


//Entrada

escreval("Introduza um número:")
leia(numero)

//processamento

se (numero mod 2=0) entao
   escreval("O número é par")
senao
   escreval("O número é impar")
fimse



Fimalgoritmo
