Algoritmo "areaquadrado"
// Este algoritmo solicita o lado e calcula a área do quadrado

Var

lado,area: real


Inicio
//entrada
escreval("-------------------------")
escreval("Digite o lado do quadrado")
escreval("-------------------------")
leia(lado)
escreval("-------------------------")

//processamento
area<-lado^2

// saída
escreval ("A área do quadrado é:",area)


Fimalgoritmo