Algoritmo "exercicio6"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cintia Pinho
// Descrição   : Ler números e somar eles
// Autor(a)    : Nicolas Garcia de Souza Santos
// Data atual  : 06/09/2022
Var
num: inteiro
resul: inteiro

Inicio

repita

escreval("Digite um número")
leia(num)

resul <- (num+resul)

escreval("A soma dos números digitados é",resul)

ate (num=0)

limpatela




Fimalgoritmo
