Algoritmo "semnome"
// Disciplina   : [Linguagem e L?gica de Programa??o]
// Professor   : Antonio Carlos Nicolodi
// Descri??o   : Escreve na tela os n?meros impares de 100 a 200
// Autor(a)    : Nicolas Garcia de Souza Santos
// Data atual  : 06/09/2022
Var
i,n: inteiro


Inicio

escreval("N?meros ?mpares de 100 a 200")

para i de 99 ate 200 faca
     se(i%2 = 1)entao
     escreval(i)
     fimse
fimpara

Fimalgoritmo