Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cintia Pinho
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nicolas Garcia de Souza Santos
// Data atual  : 11/09/2022
Var
num,resul,cont:inteiro


Inicio

escreval("digite o número com o qual deseja fazer a tabuada")
leia(num)

para cont de 1 ate 10 faca
     resul<-(num*cont)
     escreval(num," x ",cont," = ", resul)
fimpara
Fimalgoritmo