algoritmo "estoquemedio"
// Função : Calcular a média de um estoque
// Autor : Nicolas garcia de Souza Santos
// Data : 26/04/2022
// Seção de Declarações 
var

estmedio,qtdmin,qtdmax: real

inicio

//Entrada

escreval ("Digite a quantidade mínima")
leia(qtdmin)

escreval ("Digite a quantidade máxima")
leia(qtdmax)

//Processamento

estmedio <- (qtdmin+qtdmax)/2

//Saída

escreval("O estoque médio equivale a:",estmedio)

fimalgoritmo
